'use client';
import { useEffect, useMemo, useState } from 'react';
type Player = { name: string; points: number };
const tiers = [{key:'S',description:'Top 3',min:0},{key:'A',description:'1,500+',min:1500},{key:'B',description:'1,000+',min:1000},{key:'C',description:'700+',min:700},{key:'D',description:'400+',min:400},{key:'F',description:'0–399',min:0}];
function getTier(player:Player,index:number) { if(index<3)return 'S'; return tiers.find(t=>t.key!=='S'&&player.points>=t.min)?.key??'F'; }
export default function Home() { const [query,setQuery]=useState(''); const [players,setPlayers]=useState<Player[]>([]); const [loaded,setLoaded]=useState(false); useEffect(()=>{fetch('/data/players.json',{cache:'no-store'}).then(r=>r.ok?r.json():[]).then(data=>setPlayers(Array.isArray(data)?data:[])).catch(()=>setPlayers([])).finally(()=>setLoaded(true))},[]); const ranked=useMemo(()=>[...players].sort((a,b)=>b.points-a.points),[players]); const visible=ranked.filter(p=>p.name.toLowerCase().includes(query.toLowerCase())); return <main>
<div className="pixel-sky" aria-hidden="true"><i/><i/><i/><i/><i/><i/></div>
<nav className="nav wrap"><a className="brand" href="#top"><span className="brand-mark">✦</span><span>ELEMENT<br/>SMP</span></a><div className="nav-links"><a href="#rankings">Rankings</a><a href="#system">How it works</a></div><a className="season" href="#rankings"><span className="pulse"/> Season one</a></nav>
<header id="top" className="hero wrap"><p className="kicker">Element SMP</p><h1>PLAYER<br/><em>RANKINGS.</em></h1><p className="hero-copy">Rankings are based on points earned across Element SMP. The top three players are placed in S tier.</p><div className="hero-actions"><a href="#rankings" className="primary">See rankings <span>↓</span></a><span className="live-label"><i/> Updated from player data</span></div><div className="rank-strip"><div><b>06</b><small>Ranks</small></div><div><b>03</b><small>S tier spots</small></div><div><b>LIVE</b><small>Current season</small></div></div></header>
<section id="rankings" className="rankings wrap"><div className="title-row"><div><p className="kicker">Leaderboard</p><h2>TIER LIST</h2><p className="subhead">Player rankings for the current season.</p></div><label className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search player" aria-label="Search player"/></label></div><div className="tierlist">{tiers.map(tier=>{const group=visible.filter(player=>getTier(player,ranked.indexOf(player))===tier.key);return <article className={`tier tier-${tier.key.toLowerCase()}`} key={tier.key}><div className="tier-label"><span className="tier-icon" aria-hidden="true">◇</span><b>{tier.key}</b></div><div className="players">{group.length?group.map((player)=>{const placement=ranked.indexOf(player)+1;return <a className="player" key={player.name} href={`https://namemc.com/profile/${encodeURIComponent(player.name)}`} target="_blank" rel="noreferrer"><span className="placement">#{placement}</span><img className="avatar" src={`https://mc-heads.net/avatar/${encodeURIComponent(player.name)}/96`} alt=""/><span className="pname">{player.name}<small>NameMC ↗</small></span><strong>{player.points.toLocaleString()} <small>PTS</small></strong></a>;}):<div className="empty"><p>{loaded?'No players yet':'Loading...'}</p></div>}</div></article>})}</div></section>
<section id="system" className="system wrap"><p className="kicker">How it works</p><h2>PLAY. SCORE. RANK.</h2><div className="steps"><article><span>01</span><h3>Play</h3><p>Take part in Element SMP events and fights.</p></article><article><span>02</span><h3>Earn points</h3><p>Your results add to your points total.</p></article><article><span>03</span><h3>Move up</h3><p>Your score decides your tier. Top three are S tier.</p></article></div></section><footer className="wrap"><b>✦ ELEMENT SMP</b><span>Season one rankings</span></footer></main> }
