'use client';
import { useEffect, useMemo, useState } from 'react';
type Player = { name: string; points: number };
const tiers = [{key:'S',name:'Sovereign',range:'Top three champions',min:0,icon:'♛'},{key:'A',name:'Blaze',range:'1,500+ points',min:1500,icon:'◆'},{key:'B',name:'Ember',range:'1,000–1,499 points',min:1000,icon:'◆'},{key:'C',name:'Spark',range:'700–999 points',min:700,icon:'◆'},{key:'D',name:'Ash',range:'400–699 points',min:400,icon:'◆'},{key:'F',name:'Cinder',range:'0–399 points',min:0,icon:'◆'}];
function getTier(player:Player,index:number) { if(index<3)return 'S'; return tiers.find(t=>t.key!=='S'&&player.points>=t.min)?.key??'F'; }
export default function Home() { const [query,setQuery]=useState(''); const [players,setPlayers]=useState<Player[]>([]); const [loaded,setLoaded]=useState(false); useEffect(()=>{fetch('/data/players.json',{cache:'no-store'}).then(r=>r.ok?r.json():[]).then(data=>setPlayers(Array.isArray(data)?data:[])).catch(()=>setPlayers([])).finally(()=>setLoaded(true))},[]); const ranked=useMemo(()=>[...players].sort((a,b)=>b.points-a.points),[players]); const visible=ranked.filter(p=>p.name.toLowerCase().includes(query.toLowerCase())); return <main>
<div className="pixel-sky" aria-hidden="true"><i/><i/><i/><i/><i/><i/></div><div className="pixel-fire" aria-hidden="true"><b/><b/><b/><b/><b/><b/><b/><b/></div>
<nav className="nav wrap"><a className="brand" href="#top"><span className="brand-mark">✦</span><span>ELEMENT<br/>SMP</span></a><div className="nav-links"><a href="#rankings">Rankings</a><a href="#system">The system</a></div><a className="season" href="#rankings"><span className="pulse"/> Season one</a></nav>
<header id="top" className="hero wrap"><p className="kicker">The official combat rankings</p><h1>RISE.<br/><em>RULE THE ELEMENTS.</em></h1><p className="hero-copy">Every fight leaves a mark. Earn points, burn through the tiers, and take your place among Element SMP’s elite.</p><div className="hero-actions"><a href="#rankings" className="primary">View the ranks <span>↓</span></a><span className="live-label"><i/> Live leaderboard</span></div><div className="rank-strip"><div><b>06</b><small>Elemental ranks</small></div><div><b>03</b><small>Sovereigns crowned</small></div><div><b>∞</b><small>Legends to forge</small></div></div></header>
<section id="rankings" className="rankings wrap"><div className="title-row"><div><p className="kicker">Power made visible</p><h2>THE TIER LIST</h2><p className="subhead">Top three players reign in S tier. Everyone else is ranked by their total points.</p></div><label className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search player" aria-label="Search player"/></label></div><div className="tierlist">{tiers.map(tier=>{const group=visible.filter(player=>getTier(player,ranked.indexOf(player))===tier.key);return <article className={`tier tier-${tier.key.toLowerCase()}`} key={tier.key}><div className="tier-label"><span className="tier-icon">{tier.icon}</span><b>{tier.key}</b><div><strong>{tier.name}</strong><small>{tier.range}</small></div></div><div className="players">{group.length?group.map((player)=>{const placement=ranked.indexOf(player)+1;return <a className="player" key={player.name} href={`https://namemc.com/profile/${encodeURIComponent(player.name)}`} target="_blank" rel="noreferrer"><span className="placement">#{placement}</span><img className="avatar" src={`https://mc-heads.net/avatar/${encodeURIComponent(player.name)}/96`} alt=""/><span className="pname">{player.name}<small>NameMC profile ↗</small></span><strong>{player.points.toLocaleString()} <small>PTS</small></strong></a>;}):<div className="empty"><span>{tier.icon}</span><p>{loaded?'No challengers yet':'Summoning rankings...'}</p></div>}</div></article>})}</div></section>
<section id="system" className="system wrap"><p className="kicker">The elemental code</p><h2>FIGHT. EARN. ASCEND.</h2><div className="steps"><article><span>01</span><h3>Prove your power</h3><p>Take part in fights, events, and challenges across Element SMP.</p></article><article><span>02</span><h3>Feed the flame</h3><p>Each victory adds points to your total and pushes you toward the next rank.</p></article><article><span>03</span><h3>Claim the crown</h3><p>The three strongest players are crowned as the server’s S-tier Sovereigns.</p></article></div></section><footer className="wrap"><b>✦ ELEMENT SMP</b><span>Season one · Official rankings</span></footer></main> }
